card
js-tasks-ru/htmlcss-20210610_vitaly-schekin pull request #10
Opened 2021-07-05 09:11 UTC by frizar

2021-07-05 09:13 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-05 09:18 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-07-06 09:38 UTC, GSemikozov requested changes

2021-07-06 09:38 UTC, GSemikozov commented on components/card/card.css
> +  height: 367px;
только теперь когда мы добавляем содержимое и используем флекс контейнер для раскладки, фиксированную высоту можно убрать

2021-07-06 09:40 UTC, frizar commented on components/card/card.css
> +  height: 367px;
ok

2021-07-06 09:44 UTC, GSemikozov approved these changes

2021-07-06 09:44 UTC, merged