avatar
js-tasks-ru/htmlcss-20210610_vitaly-schekin pull request #11
Opened 2021-07-05 09:49 UTC by frizar

2021-07-05 09:49 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-07-06 09:41 UTC, GSemikozov requested changes

2021-07-06 09:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  border-radius: 50%;
выше уже определили это свойство

2021-07-06 09:41 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +  background-repeat: no-repeat;
тут как писал в личке скорее всего надо бы добавить еще background-position: center

2021-07-06 09:44 UTC, frizar commented on 06-lection4/01-avatar/avatar.css
> +  border-radius: 50%;
ok

2021-07-06 09:44 UTC, frizar commented on 06-lection4/01-avatar/avatar.css
> +  background-repeat: no-repeat;
ok

2021-07-06 09:45 UTC, GSemikozov approved these changes

2021-07-06 09:45 UTC, merged