Calendar
js-tasks-ru/htmlcss-20210610_vitaly-schekin pull request #8
Opened 2021-06-27 11:03 UTC by frizar

2021-06-27 11:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-27 11:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-27 12:38 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-27 13:07 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2021-06-29 08:01 UTC, GSemikozov requested changes

2021-06-29 08:01 UTC, GSemikozov commented on 05-lection3/03-calendar/calendar.css
> +  overflow: auto;
ни в коем случае такой страшный авто-скролл нам не нужен будет))

2021-06-29 09:38 UTC, frizar commented on 05-lection3/03-calendar/calendar.css
> +  overflow: auto;
ok

2021-06-29 09:39 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2021-06-29 09:46 UTC, GSemikozov approved these changes

2021-06-29 09:46 UTC, merged